### ISSUE TITLE
Anyline not initialising

### ISSUE THREAD

**Issue by jkanschik** [jkanschik/ng-anyline#1]
When starting the application, there are error messages on the console during initialisation with message "undefined" with code 20001.

Probably as a follow-up, there is a message "memory access out of bounds" with code 20003.

As a result, scanning doesn't work.

The configuration is (except of typescript and angular adjustments) the same as for the demo applications (which work).

I tried to initialise during ngOnInit, ngAfterViewInit or on click of the button. I also tried to execute outside ngZone.

**Comment by mklan** [comment]
Hello, we plan to implement better error-handling in one of our next releases. 

It seems to be an ssl issue. With ssl it threw a new error, that webGL cannot be initialized. I will try to investigate this, but I have only very basic knowledge of Angular.

**Comment by mklan** [comment]
![image](https://user-images.githubusercontent.com/5452972/82313670-f750d480-99c8-11ea-860e-1aae57aa053a.png)

**Comment by davlhd** [comment]
The WebGL message is not an error. It uses the CPU if it is not able to use the OffscreenCanvas.
Are you able to see blue dots when you try to scan?

**Comment by mklan** [comment]
One more thing. The license does not work with localhost. You need to acccess the dev server via 127.0.0.1

**Comment by jkanschik** [comment]
Thanks, seems to work. On https://127.0.0.1:4200 I can now scan without error messages.

As next steps, I try to configure the cutout and become more used to the configuration.

Thanks!
